name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - pandas
  - pandas-profiling
  - pip
  - python=3.8.3
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - rise=5.7.1