name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - fitter=1.3.0
  - altair=4.1.0
  - argon2-cffi=20.1.0
  - async-generator=1.1
  - attrs=20.2.0
  - backcall=0.2.0
  - bleach=3.1.5
  -  certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.3
  - colorlog=4.6.2
  - conda=4.8.3
  - conda-package-handling=1.7.0
  - confuse=1.3.0
  - cryptography=2.9.2
  - cv=1.0.0
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - easydev=0.10.1
  - entrypoints=0.3
  - et-xmlfile=1.0.1
  - fitter=1.3.0
  - idna=2.9
  - ImageHash=4.1.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython-genutils=0.2.0
  - ipywidgets=7.5.1
 - jdcal=1.4.1
 - jedi=0.17.2
 - Jinja2=2.11.2
 - joblib=0.16.0
 - json5=0.9.5
 - jsonschema=3.2.0
 - jupyter-client=6.1.7
 - jupyter-contrib-core=0.3.3
 - jupyter-contrib-nbextensions=0.5.1
 - jupyter-core=4.6.3
 - jupyter-highlight-selected-word=0.2.0
 - jupyter-latex-envs=1.4.6
 - jupyter-nbextensions-configurator=0.4.1
 - jupyterlab=2.2.8
 - jupyterlab-pygments=0.1.1
 - jupyterlab-server=1.2.0
 - kiwisolver=1.2.0
 - llvmlite=0.34.0
 - lxml=4.6.1
 - MarkupSafe=1.1.1
 - matplotlib=3.3.2
 - menuinst=1.4.16
 - missingno=0.4.2
 - mistune=0.8.4
 - mlxtend=0.18.0
 - nbclient=0.5.0
 - nbconvert=6.0.2
 - nbformat=5.0.7
 - nest-asyncio=1.4.0
 - networkx=2.5
 - notebook=6.1.4
 - numba=0.51.2
 - numpy=1.19.2
 - opencv-python=4.4.0.46
 - openpyxl=3.0.5
 - packaging=20.4
 - pandas=1.1.2
 - pandas-profiling=2.9.0
 - pandocfilters=1.4.2
 - parso=0.7.1
 - patsy=0.5.1 
 - pexpect=4.8.0
 - phik=0.10.0
 - pickleshare=0.7.5
 - Pillow=7.2.0
 - pip=20.0.2
 - prometheus-client=0.8.0
 - prompt-toolkit=3.0.7
 - ptyprocess=0.6.0
 - pycosat=0.6.3
 - pycparser=2.2
 - Pygments=2.7.0
 - pyOpenSSL=19.1.0
 - pyparsing=2.4.7
 - pyrsistent=0.17.3
 - PySocks=1.7.1
 - python-dateutil=2.8.1
 - pytz=2020.1
 - PyWavelets=1.1.1
 - pywin32=227
 - pywinpty=0.5.7
 - PyYAML=5.3.1
 - pyzmq=19.0.2
 - requests=2.23.0
 - rise=5.7.1
 - ruamel-yaml=0.15.87
 - scikit-learn=0.23.2
 - scipy=1.5.2
 - seaborn=0.11.0
 - Send2Trash=1.5.0
 - setuptools=46.4.0.post20200518
 - six=1.14.0
 - statsmodels=0.12.0
 - tangled-up-in-unicode=0.0.6
 - terminado=0.8.3
 - testpath=0.4.4
 - threadpoolctl=2.1.0
 - toolz=0.11.1
 - tornado=6.0.4
 - tqdm=4.46.0
 - traitlets=5.0.4
 - urllib3=1.25.8
 - vboxapi=1
 - vega-datasets=0.9.0
 - visions=0.5.0
 - wcwidth=0.2.5
 - webencodings=0.5.1
 - wheel=0.34.2
 - widgetsnbextension=3.5.1
 - win-inet-pton=1.1.0
 - wincertstore=0.2
 - xlrd=1.2.0

  


