name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - altair_saver
  - beautifulsoup4=4.9
  - h5py=2.10
  - ipywidgets=7.5
  - jupyterlab=2.1.3
  - matplotlib-base=3.2
  - nodejs
  - numba=0.48
  - numpy
  - pandas=1.1.2
  - pandas-profiling
  - pip=20.0.2
  - pillow
  - python=3.7
  - rise
  - scikit-image=0.16
  - scikit-learn=0.22
  - scipy=1.4
  - seaborn=0.11
  - statsmodels=0.11
  - sympy=1.5
  - vega_datasets
  - xlrd=1.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython-genutils=0.2.0
  - ipywidgets=7.5.1
  - jdcal=1.4.1
  - jedi=0.17.2
  - Jinja2=2.11.2
  - joblib=0.16.0
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-client=6.1.7
  - jupyter-contrib-core=0.3.3
  - jupyter-contrib-nbextensions=0.5.1
  - jupyter-core=4.6.3
  - jupyter-highlight-selected-word=0.2.0
  - jupyter-latex-envs=1.4.6
  - jupyter-nbextensions-configurator=0.4.1
  - jupyterlab=2.2.8
  - jupyterlab-pygments=0.1.1
  - jupyterlab-server=1.2.0
  - rise=5.7.1
  - ruamel-yaml=0.15.87
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0



