name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - altair_saver=4.1.0
  - beautifulsoup4=4.9.3
  - h5py=3.1.0
  - ipywidgets=7.5
  - jupyterlab=3.0.1
  - matplotlib-base=3.3.2
  - nodejs
  - numba=0.48
  - numpy
  - pandas=1.2.0
  - pandas-profiling=2.10.0
  - pip=20.3.3
  - pillow=8.1.0
  - python=3.7
  - rise=5.7.1
  - scikit-image=0.18.1
  - scikit-learn=0.24.0
  - scipy=1.6.0
  - seaborn=0.11.1
  - statsmodels=0.11
  - sympy=1.5.2
  - vega_datasets
  - xlrd=1.2.6
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-client=6.1.7
  - jupyter-contrib-core=0.3.3
  - jupyter-contrib-nbextensions=0.5.1
  - jupyter-core=4.7.0
  - jupyter-highlight-selected-word=0.2.0
  - jupyter-latex-envs=1.4.6
  - jupyter-nbextensions-configurator=0.4.1
  - jupyterlab-pygments=0.1.2
  - jupyterlab-server=2.1.0