name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - altair_saver
  - beautifulsoup4=4.9
  - h5py=2.10
  - ipywidgets=7.5
  - jupyterlab=2.2.8
  - matplotlib-base=3.2
  - nodejs
  - numba=0.48
  - numpy
  - pandas=1
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - rise=5.7.1
  - scikit-image=0.16
  - scikit-learn=0.23.2
  - scipy=1.4
  - seaborn=0.11
  - statsmodels=0.11
  - sympy=1.5.2
  - vega_datasets
  - xlrd=1.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-client=6.1.7
  - jupyter-contrib-core=0.3.3
  - jupyter-contrib-nbextensions=0.5.1
  - jupyter-core=4.6.3
  - jupyter-highlight-selected-word=0.2.0
  - jupyter-latex-envs=1.4.6
  - jupyter-nbextensions-configurator=0.4.1
  - jupyterlab-pygments=0.1.1
  - jupyterlab-server=1.2.0